# Generated by Django 4.1.7 on 2023-03-24 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('side_panel', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('cabinet_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CaseFan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('rpm', models.CharField(max_length=100)),
                ('airflow', models.CharField(max_length=100)),
                ('noise_level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer', to='velocityapi.case')),
            ],
        ),
        migrations.CreateModel(
            name='CpuCooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('is_water_cooled', models.BooleanField(default=False)),
                ('rpm', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('noise_level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=400)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('storage_interface', models.CharField(max_length=100)),
                ('memory', models.CharField(max_length=100)),
                ('clockSpeed', models.CharField(max_length=100)),
                ('chipset', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('backlit', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('wireless', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('form_factor', models.CharField(max_length=100)),
                ('chipset', models.CharField(max_length=100)),
                ('memory_slots', models.CharField(max_length=100)),
                ('socket_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('tracking_method', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('wireless', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('power', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('efficiency', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('speed', models.CharField(max_length=100)),
                ('socket_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('m2', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=500)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer', to='velocityapi.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer_favorites', to='velocityapi.computer')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_favorites', to='velocityapi.customer')),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='cpu_cooler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer', to='velocityapi.cpucooler'),
        ),
        migrations.AddField(
            model_name='computer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer_customer', to='velocityapi.customer'),
        ),
        migrations.AddField(
            model_name='computer',
            name='gpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer', to='velocityapi.gpu'),
        ),
        migrations.AddField(
            model_name='computer',
            name='keyboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer', to='velocityapi.keyboard'),
        ),
        migrations.AddField(
            model_name='computer',
            name='likes',
            field=models.ManyToManyField(related_name='computers_favorited', through='velocityapi.Favorite', to='velocityapi.customer'),
        ),
        migrations.AddField(
            model_name='computer',
            name='motherboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer', to='velocityapi.motherboard'),
        ),
        migrations.AddField(
            model_name='computer',
            name='mouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer', to='velocityapi.mouse'),
        ),
        migrations.AddField(
            model_name='computer',
            name='power_supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer', to='velocityapi.powersupply'),
        ),
        migrations.AddField(
            model_name='computer',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer', to='velocityapi.processor'),
        ),
        migrations.AddField(
            model_name='computer',
            name='ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer', to='velocityapi.ram'),
        ),
        migrations.AddField(
            model_name='computer',
            name='ssd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer', to='velocityapi.ssd'),
        ),
    ]
